apiVersion: v1
kind: EphemeralContainers
metadata:
  name: ephemeral-sidecar
EphemeralContainers:
  - name: sidecar
    image: mjrousos/sidecar:latest
    stdin: true
    tty: true
    volumeMounts:
      - name: tmp
        mountPath: /tmp  